### ISSUE TITLE
Why S3 bucket can't enfoce by tags?

### ISSUE THREAD

**Issue by ajiraj2411** [awsdocs/amazon-s3-user-guide#4]
We need to enforce S3 bucket based on Some Tags. While checking S3 Action condition Keys there is no aws:RequestTag option. Is there a reason for that?

Can anyone help me to fix this problem?

**Comment by panjws** [comment]
Hi @AjithKumar-Raj,

Please checkout out  https://docs.aws.amazon.com/AmazonS3/latest/dev/CostAllocTagging.html

If you want further support on S3, you can:
•	Post your questions on the Amazon S3 discussion forum at https://forums.aws.amazon.com/
•	Or contact Technical Support at https://aws.amazon.com/contact-us/


If there is something specific missing/incorrect in the docs please let us know.

Best regards.
