### ISSUE TITLE
S3 event notification limits

### ISSUE THREAD

**Issue by brainstorm** [awsdocs/amazon-s3-user-guide#5]
Should this page detail how many S3 event notifications are supported?

https://github.com/awsdocs/amazon-s3-user-guide/blob/master/doc_source/setup-event-notification-destination.md

I vaguely recall it was around ~1000 concurrent events for S3, but I cannot easily find it :/

**Comment by aws-alan** [comment]
Content has been restructured in the new Amazon S3 User guide.
